name = "stat-tracker-sync"
main = "worker.mjs"
compatibility_date = "2026-09-18"

[vars]
ALLOWED_ORIGINS = "https://stattrackerv4.stream,https://www.stattrackerv4.stream"

[[d1_databases]]
binding = "DB"
database_name = "stat-tracker"
database_id = "85e22afb-5251-4eca-9f1c-4b0875ebf5f9"
